# Opciones de financiamiento para el proyecto

# Contacto para servicios profesionales y consultoría
custom: ["https://datoscout.ec", "mailto:solutions@datoscout.ec"]

# GitHub Sponsors (cuando esté disponible)
# github: [datascout-ecuador]

# Información de contacto para empresas
# Para servicios profesionales de implementación de IA
# Consultoría especializada en transformación digital
# Entrenamiento corporativo en herramientas de IA
# solutions@datoscout.ec 